export const V1_ACTIVE_GOVERNORS_FALLBACK = 150;

export const V1_POOL_ATTENTION_QUORUM_FRACTION = 0.2;
export const V1_POOL_UPVOTE_FLOOR_FRACTION = 0.1;

export const V1_CHAMBER_QUORUM_FRACTION = 0.33;
export const V1_CHAMBER_PASSING_FRACTION = 2 / 3; // 66.6%
